### ISSUE TITLE
[feature-request] btrfs support

### ISSUE THREAD

**Issue by Gottox** [siderolabs/extensions#199]
I'm currently trying to integrate an already existing file system into talos and make it available to pods running on one node. As this pre-existing file system is based on btrfs, I'd like to add btrfs support to the talos-os. As talos is aiming to reduce attack surfaces, I think it makes the most sense to add support as an extension.

# other solutions I considered

I also considered switching from btrfs to zfs, which is already supported by talos and has a similiar featureset. Unfortunately, depending systems use btrfs send/receive features and cannot easily be migrated to other filesystems.
```[tasklist]
### Tasks
- [x] build kernel with btrfs support in @siderolabs/pkgs
- [x] install kernel module into own package
- [x] add extension to @siderolabs/extensions linking the package
```

**Comment by frezbo** [comment]
We're happy to support btrfs as  an extension, PR's welcome

**Comment by Gottox** [comment]
Thanks for your quick reply? Is the tasklist complete?

**Comment by Gottox** [comment]
Is the `thunderbold` package a good template to base my work on?

**Comment by Gottox** [comment]
@frezbo this is my first contribution to the talos OS. Bear with me! ^^

**Comment by Gottox** [comment]
Quick question as I saw https://github.com/siderolabs/talos/pull/7622: Is this extensions available 1.5.0 final?
